config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :movies
  devise_for :users
  get '/mymovies', to: 'movies#profile' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validate :image_type

  def self.search(term)
    if term
      where('LOWER(title) LIKE ?', "%#{term.downcase}%").order('id DESC')
    else
      order('id DESC') 
    end
  end

  private
  def image_type
    if image.attached? == false
      errors.add(:image, "is missing!")
    end
    if !image.content_type.in?(%w(image/jpeg image/jpg image/png))
      errors.add(:image, 'Must be a JPEG, JPG or PNG file')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :profile]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.search(params[:term])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  def profile
    :authenticate_user
    @movies = Movie.where(user_id: current_user.id)
  end

  # GET /movies/new
  def new
    :authenticate_user
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    :authenticate_user
  end

  # POST /movies
  # POST /movies.json
  def create
    :authenticate_user
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    :authenticate_user
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    authorize @movie
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :genre, :director, :duration, :description, :image, :user_id, :term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviesss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <%= link_to('Home', root_path) %>
      <% if user_signed_in? %>
        <%= link_to('My Movies', mymovies_path) %>
        <%= link_to 'Upload Movie', new_movie_path %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link m-2 menu-item") %>
      <% else %>
        <%= link_to('Log In', new_user_session_path)  %>
        <%= link_to('Register Now', new_user_registration_path)  %>
      <% end %>
      <br>
      <%= form_tag(root_path, method: :get) do %>
      <%= text_field_tag :term, nil, placeholder: "Search by title.." %>
      <%= submit_tag 'Search' %>
    <% end %>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Movies</h1>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Title</th>
      <th>Year</th>
      <th>Genre</th>
      <th>Uploaded By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= image_tag(movie.image, width: '100') %></td>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.user.email %></td>
        <td><%= link_to 'View', movie %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/profile.html.erb
<p id="notice"><%= notice %></p>

<h1>My Movies</h1>

<% if @movies.length == 0 %>
<h3>You havent uploaded any movies</h3>
<%= link_to 'Upload one now!', new_movie_path %>
<% else %>
<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Year</th>
      <th>Title</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= image_tag(movie.image, width: '100') %></td>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.genre %></td>
        <td><%= link_to 'View', movie %></td>
        <% if movie.user_id == current_user.id  %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <strong><%= @movie.title %></strong>
  
</h1>
<p>
  <%= image_tag(@movie.image, width: '300') %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @movie.duration %> minutes
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Uploaded By:</strong>
  <%= @movie.user.email %>
</p>

<% if @movie.user == current_user  %>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
  <%= link_to 'Delete', @movie, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', movies_path %>